variables:
  DOCKER_BUILD_ARGS: --build-arg ROSSUM_PYPI_USERNAME=gitlab-ci-token --build-arg ROSSUM_PYPI_PASSWORD=$CI_JOB_TOKEN

include:
  - project: common/gitlab-ci
    file: /templates/gitlab-ci-simple.yaml

test:
  stage: test
  image: ${REGISTRY_BASE}/${CI_PROJECT_PATH}:tmp_sha.${CI_COMMIT_SHA}
  variables:
    GIT_STRATEGY: none
  script:
    - cd /app
    - pytest tests --cov --cov-report=term --cov-report=xml:coverage.xml --junitxml=junit.xml
  # Extract the total coverage percentage for the pipeline badge
  coverage: '/(?i)TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      # Powers the red/green annotations on MR diffs
      coverage_report:
        coverage_format: cobertura
        path: /app/coverage.xml
      junit: /app/junit.xml
    paths:
      - /app/coverage.xml
      - /app/junit.xml
  needs: [build-docker-image]
