name: Build and Release Deployment Manager

on:
  push:
    tags:
      - "v*.*.*"
  workflow_run:
    workflows: ["Auto Tag on Merge"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry & Plugins
        run: pip install poetry poetry-dynamic-versioning

      - name: Install Dependencies
        run: poetry install

      - name: Build Wheel
        run: poetry build

      - name: Install git-cliff (for Changelog)
        run: |
          curl -fsSL https://github.com/orhun/git-cliff/releases/latest/download/git-cliff-$(uname -s)-$(uname -m) -o git-cliff
          chmod +x git-cliff
          sudo mv git-cliff /usr/local/bin/

      - name: Generate Changelog from Commits
        run: |
          git-cliff --unreleased --tag "${{ github.ref_name }}" --output CHANGELOG_TMP.md
          cat CHANGELOG.md >> CHANGELOG_TMP.md  # Append existing changelog
          mv CHANGELOG_TMP.md CHANGELOG.md  # Replace with updated version

      - name: Upload Release to GitHub with Changelog
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
          tag_name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
