name: Build and Release Deployment Manager

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get Latest Tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag detected: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Install Poetry & Plugins
        run: pip install poetry poetry-dynamic-versioning

      - name: Install Dependencies
        run: poetry install

      - name: Build Wheel
        run: poetry build

      - name: Install git-cliff (for Changelog)
        run: |
          CLIFF_URL=$(curl -s https://api.github.com/repos/orhun/git-cliff/releases/latest | jq -r '.assets[].browser_download_url' | grep '.deb' | head -n 1)

          if [ -z "$CLIFF_URL" ]; then
            echo "❌ Could not find a git-cliff .deb release."
            exit 1
          fi

          echo "Downloading from: $CLIFF_URL"
          curl -fsSL "$CLIFF_URL" -o git-cliff.deb

          echo "Installing git-cliff..."
          sudo dpkg -i git-cliff.deb

          echo "✅ git-cliff installed successfully!"

      - name: Generate Changelog from Commits
        run: |
          git-cliff --config cliff.toml --tag "${{ env.latest_tag }}" --output CHANGELOG_TMP.md
          cat CHANGELOG.md >> CHANGELOG_TMP.md  # Append existing changelog
          mv CHANGELOG_TMP.md CHANGELOG.md  # Replace with updated version

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.latest_tag }}
          name: "${{ env.latest_tag }}"
          files: dist/*.whl
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
