name: Build and Release Deployment Manager

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry & Plugins
        run: pip install poetry poetry-dynamic-versioning

      - name: Install Dependencies
        run: poetry install

      - name: Build Wheel
        run: poetry build

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
