name: Build and Release Deployment Manager

on:
  push:
    tags:
      - "v*.*.*"  # Runs when a version tag (e.g., v2.1.0) is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry

      - name: Build Wheel
        run: |
          poetry build
          WHEEL_NAME=$(ls dist/*.whl)
          mv "$WHEEL_NAME" "dist/deployment_manager-latest-py3-none-any.whl"

      - name: Upload Release to GitHub (Versioned)
        uses: softprops/action-gh-release@v2
        with:
          files: dist/deployment_manager-latest-py3-none-any.whl
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload "Latest" Wheel (Overwrite Previous Latest)
        uses: softprops/action-gh-release@v2
        with:
          files: dist/deployment_manager-latest-py3-none-any.whl
          tag_name: latest
          draft: false
          prerelease: false
