name: Build and Release Deployment Manager

on:
  push:
    tags:
      - "v*.*.*" # Runs when a version tag (e.g., v2.1.0) is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code with Full History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures all Git tags are available

      - name: Install Poetry & Plugins
        run: |
          pip install poetry poetry-dynamic-versioning

      - name: Verify Git Tags
        run: git tag

      - name: Build the Wheel with Correct Version
        run: |
          poetry lock --no-update
          poetry install
          poetry build

      - name: Find the Generated Wheel
        id: find_wheel
        run: echo "WHEEL_FILE=$(ls dist/*.whl)" >> $GITHUB_ENV

      - name: Upload Release to GitHub (Versioned)
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.WHEEL_FILE }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
